### ISSUE TITLE
crash when exception is raised

### ISSUE THREAD

**Issue by vgrafe** [interuss/monitoring#454]
Hi!

Some recent changes make our USS fail the qualifier test, which fails in a runtime error due to trying to use an undefined variable. This causes a crash in the mock USS, which outputs the following error and also breaks the html output:

```
2023-12-29 02:50:09.205 | ERROR    | monitoring.uss_qualifier.suites.suite:_run_test_scenario:174 - Execution error:
  Traceback (most recent call last):
    File "/app/monitoring/uss_qualifier/scenarios/astm/utm/data_exchange_validation/test_steps/expected_interactions_test_steps.py", line 118, in mock_uss_interactions
      interactions, query = mock_uss.get_interactions(since)
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/app/monitoring/uss_qualifier/resources/interuss/mock_uss/client.py", line 108, in get_interactions
      raise QueryError(
  monitoring.monitorlib.fetch.QueryError: Request to mock uss http://scdsc.log.uss6.localutm/mock_uss/interuss_logging/logs?from_time=2023-12-29T02:50:08.962042Z returned a 500

  During handling of the above exception, another exception occurred:

  Traceback (most recent call last):
    File "/app/monitoring/uss_qualifier/suites/suite.py", line 156, in _run_test_scenario
      scenario.run(context)
    File "/app/monitoring/uss_qualifier/scenarios/astm/utm/data_exchange_validation/get_op_data_validation.py", line 152, in run
      self._plan_successfully_test_case(times)
    File "/app/monitoring/uss_qualifier/scenarios/astm/utm/data_exchange_validation/get_op_data_validation.py", line 208, in _plan_successfully_test_case
      tested_uss_notifications, _ = mock_uss_interactions(
                                    ^^^^^^^^^^^^^^^^^^^^^^
    File "/app/monitoring/uss_qualifier/scenarios/astm/utm/data_exchange_validation/test_steps/expected_interactions_test_steps.py", line 124, in mock_uss_interactions
      summary=f"Error from mock_uss when attempting to get interactions from_time {st}",
                                                                                   ^^
  NameError: name 'st' is not defined
```

The faulty LOC is here: https://github.com/interuss/monitoring/blame/280675b00fe9c50b222a629c9619f4fee525fe48/monitoring/uss_qualifier/scenarios/astm/utm/data_exchange_validation/test_steps/expected_interactions_test_steps.py#L124

**Comment by vgrafe** [comment]
It might be relevant to add this here - there might be a bug in the mock USS that causes an exception to be raised, leading to this error while handling the exception.

In the sequence 12, the step 29 is a call to get logs from the mock USS. It crashes with a http500, with the following message: `Unhandled TypeError: At query.response.json: 'int' object is not iterable`.

[report.json.zip](https://github.com/interuss/monitoring/files/13794976/report.json.zip)

**Comment by vgrafe** [comment]
The USS mock seems to be crashing when parsing a log line here: https://github.com/interuss/monitoring/blob/280675b00fe9c50b222a629c9619f4fee525fe48/monitoring/mock_uss/interaction_logging/routes_interactions_log.py#L41C1-L41C1

**Comment by vgrafe** [comment]
In case it helps, I added a print statement on `obj`, which output the following just before the crash.

```python
{
  'query': {
    'request': {
      'method': 'POST',
      'url': 'http://scdsc.uss1.localutm/uss/v1/operational_intents/',
      'initiated_at': '2023-12-28T02:21:16.905597Z',
      'headers': {
        'User-Agent': 'python-requests/2.31.0',
        'Accept-Encoding': 'gzip, deflate, br',
        'Accept': '*/*',
        'Connection': 'keep-alive',
        'Content-Length': '2113',
        'Content-Type': 'application/json',
        'Authorization': 'EDITED'
      },
      'json': {
        'operational_intent_id': 'f76b53ee-b6e8-4660-899e-13fc9e14c1fd',
        'operational_intent': {
          'reference': {
            'id': 'f76b53ee-b6e8-4660-899e-13fc9e14c1fd',
            'manager': 'uss6',
            'uss_availability': 'Unknown',
            'version': 1,
            'state': 'Accepted',
            'ovn': 'BGYkAFbF4JH7q-rVDq8G0vofjzELEi3N1DEpgL8.JJQ_',
            'time_start': {
              'value': '2023-12-28T02:20:50.250213Z',
              'format': 'RFC3339'
            },
            'time_end': {
              'value': '2023-12-28T02:25:50.250213Z',
              'format': 'RFC3339'
            },
            'uss_base_url': 'http://scdsc.log.uss6.localutm/mock/scd',
            'subscription_id': '528b4206-9b4e-44be-9d01-4142f2fa298e'
          },
          'details': {
            'volumes': [
              {
                'volume': {
                  'outline_polygon': {
                    'vertices': [
                      {
                        'lat': 32.7258,
                        'lng': -96.75935
                      },
                      {
                        'lat': 32.72406,
                        'lng': -96.75554000000001
                      },
                      {
                        'lat': 32.71379,
                        'lng': -96.75811
                      },
                      {
                        'lat': 32.72563,
                        'lng': -96.76905000000001
                      },
                      {
                        'lat': 32.71785,
                        'lng': -96.75857
                      }
                    ]
                  },
                  'altitude_lower': {
                    'value': 93.0,
                    'reference': 'W84',
                    'units': 'M'
                  },
                  'altitude_upper': {
                    'value': 151.0,
                    'reference': 'W84',
                    'units': 'M'
                  }
                },
                'time_start': {
                  'value': '2023-12-28T02:20:50.250213Z',
                  'format': 'RFC3339'
                },
                'time_end': {
                  'value': '2023-12-28T02:25:50.250213Z',
                  'format': 'RFC3339'
                }
              }
            ],
            'off_nominal_volumes': [
              
            ],
            'priority': 0
          }
        },
        'subscriptions': [
          {
            'subscription_id': '2880267a-db92-4e7e-b854-056dafe75907',
            'notification_index': 40
          },
          {
            'subscription_id': '2fa50cc6-2dc1-4372-84cb-8f8e9c087a20',
            'notification_index': 31
          },
          {
            'subscription_id': '4c44bddc-afc5-429f-909d-c365836cdc95',
            'notification_index': 42
          },
          {
            'subscription_id': '7f60828b-640d-4dd5-ab30-cb53935b058a',
            'notification_index': 43
          },
          {
            'subscription_id': '83793b8e-42bc-415e-a7f9-18d58ac3cb1c',
            'notification_index': 39
          },
          {
            'subscription_id': '8aeeeccd-079a-4070-911b-36eb22473dd7',
            'notification_index': 32
          },
          {
            'subscription_id': '97cf5e31-d0aa-440d-8c3d-c2d63066983c',
            'notification_index': 23
          },
          {
            'subscription_id': 'abec9f9e-7ed7-4ba3-ba5d-fe5f7a0f661b',
            'notification_index': 17
          },
          {
            'subscription_id': 'c851fe37-7b51-4ef8-8a87-60567d8f3560',
            'notification_index': 29
          },
          {
            'subscription_id': 'e96b2001-c601-4310-b4e8-0fda99d27d3b',
            'notification_index': 45
          }
        ],
        'request_id': '057c3e7a-c730-4410-80d9-05e43431a9fb'
      },
      'body': None
    },
    'response': {
      'code': 200,
      'headers': {
        'date': 'Thu, 28 Dec 2023 02:21:16 GMT',
        'server': 'uvicorn',
        'content-length': '3',
        'content-type': 'application/json'
      },
      'elapsed_s': 0.031217,
      'reported': '2023-12-28T02:21:16.987028Z',
      'json': 204,
      'body': None
    },
    'query_type': 'astm.f3548.v21.uss.notifyOperationalIntentDetailsChanged'
  },
  'direction': 'Outgoing'
}
```

**Comment by vgrafe** [comment]
Apologies - it looks like at least one of the services I was running locally was not behaving properly. Everything runs fine after pruning all docker resources and rebuilding everything.

Since the initial issue has a PR about to be merged, I'll close this.

**Comment by BenjaminPelletier** [comment]
I'm glad it's not causing you problems any more, but a 500 from mock_uss is probably a bug regardless of other system behavior -- I'll see if there's anything else I can find out.

**Comment by vgrafe** [comment]
I've not dug super far, so my uneducated guess is as follow: I tend to just pull the latest commit on `main` and sometimes restart mocks or DSS via makefile, and maybe some running service went out of sync that way. So maybe logs were written/stored (by a service that was not rebuilt/behaving as it should have) in a format/shape that were not compatible with the parsing logic of the running mock.
